export const LOAD_CATALOG_LOADING = "LOAD_CATALOG_LOADING";
export const LOAD_CATALOG_SUCCESS = "LOAD_CATALOG_SUCCESS";
export const LOAD_CATALOG_ERROR = "LOAD_CATALOG_ERROR";
export const SET_PRODUCT_INFO = "SET_PRODUCT_INFO";
export const SET_PRODUCT_CART = "SET_PRODUCT_CART";
